### ISSUE TITLE
Unable to setup Warp with CUDA enabled - incompatible Visual Studio 2022

### ISSUE THREAD

**Issue by NagabhushanSN24** [maria-korosteleva/NvidiaWarp-GarmentCode#1]
Hi Maria,

Thanks for open-sourcing the project. I am trying to setup the Warp simulator to generate garment meshes from garment code/sewing pattern json specification.

When building the project with `python build_lib.py`, I get the below error.

```
warp.cu
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
```

I have installed Visual Studio 2022 community edition (v 17.11.12) and cuda 12.1. This is on Windows 11 machine. Any suggestions or pointers?

PS: I am able to install warp without cuda support by removing the CUDA_PATH env variable

**Comment by maria-korosteleva** [comment]
Hi @NagabhushanSN24 
The error is not related to our project =) Quick search points to this question about CUDA/VS versions mismatch with some solutions suggested: https://stackoverflow.com/questions/78515942/cuda-compatibility-with-visual-studio-2022-version-17-10

Let me know if any of solutions work! I will then add this link to the Readme for others to reference =)

**Comment by NagabhushanSN24** [comment]
Thanks Maria, for the quick reply. I'll check this out and update here.

**Comment by NagabhushanSN24** [comment]
This helped! I couldn't downgrade Visual Studio. Instead, I upgraded my coda to 12.6. It is working now, thanks!
